### PR TITLE
Prevent deprecation warning in node 7.4.0

### PR DESCRIPTION
**Pull request by borisdiakur**
Closes https://github.com/tmpvar/repl.history/issues/10

### CODE REVIEW

**Comment by eush77** [comment]
I think that the callback should check and throw any potential errors instead of just silencing them.

**Comment by borisdiakur** [comment]
@eush77 How about printing a warning as an alternative? This wouldn’t change the current behaviour of the module.

**Comment by eush77** [comment]
I don't think printing would be wise here since it leaves no way to handle the error and can mess up with the repl prompt. And this module already throw errors related to the history file since it uses `openSync` and `closeSync`.

Alternatively, would you feel positive about changing `write` to `writeSync` here?

**Comment by borisdiakur** [comment]
@eush77 [The `fs` docs](https://nodejs.org/api/fs.html#fs_fs_write_fd_string_position_encoding_callback) say:

> Note that it is unsafe to use fs.write multiple times on the same file without waiting for the callback. For this scenario, fs.createWriteStream is strongly recommended.

So I would actually follow the recommendation and use `fs.createWriteStream`. What do you think?

**Comment by borisdiakur** [comment]
Ping (mr is ready to merge).

**Comment by tmpvar** [comment]
thanks - published 0.1.4

**Pull request merged**
